# Generated by Django 3.2.7 on 2021-09-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GitHub_Profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='users_data',
        ),
    ]
